bloodbank/bloodbank/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("bloodbankapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloodbank/bloodbankapp/urls.py
from django.urls import path
from . import views
app_name='bloodbankapp'
urlpatterns=[
    path('',views.home,name='home'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    # path('profile/',views.profile,name='profile'),
    path('patientdetails/',views.patientdetails,name='patientdetails'),
    path('donordetails/',views.donordetails,name='donordetails'),
    path('success',views.success,name='success'),
    path('adminview/',views.adminview,name='adminview'),
    path('p_signup/',views.p_signup,name='p_signup'),
    path('plogin/',views.p_login,name='p_login'),
    path('patient_dashboard/',views.patient_dashboard,name='patient_dashboard'),
    path('approve/<int:patient_id>/', views.approve_patient, name='approve_patient'),



]

bloodbank/templates/patient/patient_dashboard.html
{% extends 'index.html' %}
{% block content %}
<div class="row pdash">
<div class="container d-flex flex-column align-items-center col-md-5 col-8 mt-5">
    <h2 style="color:blue">Welcome, {{ patient.name|title }}</h2>
    <h4>Your blood request details:</h4>
    <ul>
        <li>Age: {{ patient.age }}</li>
        <li>Gender: {{ patient.gender }}</li>
        <li>Blood Group: {{ patient.bloodgroup }}{{ patient.rhoptions }}</li>
        <li>Units Needed: {{ patient.unit }}</li>
        <li>Hospital: {{ patient.hospital }}</li>
        <li>City: {{ patient.location }}</li>
    </ul>

    <hr>

    <h4>Donors who donated to you:</h4>
    {% if donors %}
    <div class="donorupdate col-8 col-md-5">
        <div>
        {% for donor in donors %}
            <img src="{{donor.image.url}}" style="max-width:250px; max-height:200px; width:250px; height:200px; object-fit:cover;" 
                 class="img-fluid rounded mt-2"> 
            <h3>{{ donor.username }}</h3> 
            <h3>({{ donor.unit }} units)</h3>
        {% endfor %}
       </div>
    {% else %}
        <p>No donors have donated yet.</p>
    {% endif %}
    </div>
</div>
</div>
{% endblock %}

bloodbank/templates/patient/patientdetails.html
{% extends 'index.html' %}

{% block content %}
  
  <div class="container-fluid">
    <div class="row d-flex justify-content-center mt-5">
        <div class="col-4">
            <h5>kindly fill this form</h5>  
            <div class=" my-3">
                <form method="post" >
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name" class="form-label"required >Patient's Name</label>
                        <input type="text" class="form-control" id="name" name="name" autocomplete="off">
                    </div>
                     <div class="form-group">
                        <label for="age" class="form-label"required >Age</label>
                        <input type="number" class="form-control" id="age" name="age" autocomplete="off">
                    </div>
                    <div required >
                    <label class="form-label">Gender</label>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="gender" id="male" value="M" required autocomplete="off">
        <label class="form-check-label" for="male">
            Male
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="gender" id="female" value="F">
        <label class="form-check-label" for="female">
            Female
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="gender" id="other" value="O">
        <label class="form-check-label" for="other">
            Other
        </label>
    </div>
</div>
     <label for="blood-grp"> blood group</label>
    <div class="input-group" required >
    <input type="text" id="blood-grp" name="bloodgroup"  style="width:50px">
    <select name="rhoptions">
        <option value="">RH</option>
        <option value="+">+</option>
        <option value="-">-</option>
    </select>
   </div>
     <div class="form-group">
                        <label for="unit" class="form-label">Required unit</label>
                        <input type="number" class="form-control" id="unit" name="unit"required  autocomplete="off">
                    </div>
        <div class="form-group">
                        <label for="hospital" class="form-label">Hospital Name</label>
                        <input type="text" class="form-control" id="hospital" name="hospital"required  autocomplete="off">
                    </div>
        <div class="form-group">
                        <label for="location" class="form-label">Address</label>
                        <input type="text-area" class="form-control" id="location" name="location"required  autocomplete="off">
                    </div>
                    
                     <div class="form-group">
                        <label for="ifany" class="form-label">if any(optional)</label>
                        <input type="text-area" class="form-control" id="ifany" name="ifany" autocomplete="off">
                    </div>
                    <div class="my-3 d-flex justify-content-center">
                        <button type="submit" class="btn btn-primary">submit</button>
                    </div>
                   
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

bloodbank/templates/patient/patientreg.html
{% extends 'index.html' %}

{% block content %}
  
  <div class="container-fluid">
    <div class="row d-flex justify-content-center mt-5 loginsubdiv1">
        <div class="col-md-4 col-12 loginsubdiv2">
            <h3 class="subheading">Register</h3>
           {% if error %}
          <div style="color: red;">
             {{ error }}
           </div>
        {% endif %}
            <div class=" my-3 loginform">
                <form method="post" >
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username" class="form-label">Name</label>
                        <input type="text" class="form-control" id="username" name="p_name" autocomplete="off">
                    </div>
              <div class="form-group">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" class="form-control" id="email" name="p_email" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" class="form-control" id="password" name="p_password" autocomplete="off">
                    </div>
                    <div class="form-group">
                        <label for="confirm_pass" class="form-label">Confirm Password</label>
                        <input type="password" class="form-control" id="confirm_pass" name="confirm_pass" autocomplete="off">
                    </div>

                    
                    <div class="my-3 d-flex justify-content-center">
                        <button type="submit" class="btn btn-primary loginbtn">Register</button>
                    </div>
                    <div  class="my-3 d-flex justify-content-center">
                        <a href="{% url 'bloodbankapp:p_login' %}" style="color:white"> Already have an account?</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}