bloodbank/bloodbank/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("bloodbankapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bloodbank/bloodbankapp/urls.py
from django.urls import path
from . import views
app_name='bloodbankapp'
urlpatterns=[
    path('',views.home,name='home'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    # path('profile/',views.profile,name='profile'),
    path('patientdetails/',views.patientdetails,name='patientdetails'),
    path('donordetails/',views.donordetails,name='donordetails'),
    path('success',views.success,name='success'),
    path('adminview/',views.adminview,name='adminview'),
    path('p_signup/',views.p_signup,name='p_signup'),
    path('plogin/',views.p_login,name='p_login'),
    path('patient_dashboard/',views.patient_dashboard,name='patient_dashboard'),
    path('approve/<int:patient_id>/', views.approve_patient, name='approve_patient'),



]

bloodbank/templates/donor/dashboard.html
{% extends 'index.html' %}

{% block content %}

<div class="container-fluid  blue">
    <div class="row">
        <h2 class="subheading">Patient's Details</h2>
    </div>

    <div class="row m-3">
        {% for d in data %}
        <div class="col-md-4 col-12 mb-4 pdata">
            <div class="card pcard">
                <div class="card-body">
                    <div class="row">
                       

                        <div class="content col-md-8">
                            <p>Name: {{ d.name }}</p>
                            <p>Age: {{ d.age }}</p>
                            <p>Gender: {{ d.gender }}</p>
                            <p>Bloodgroup: {{ d.bloodgroup }}{{ d.rhoptions }}</p>
                            <p>Unit: {{ d.unit }}</p>
                            <p>Hospital: {{ d.hospital }}</p>
                            <p>Location: {{ d.location }}</p>
                            <pclass="message">Message: {{ d.ifany }}</p>

                            <div>
                               <a href="#" class="btn btn-primary" 
   data-bs-toggle="modal" 
   data-bs-target="#donateModal"
   data-patient-id="{{ d.id }}"
   data-patient-name="{{ d.name }}">
   Donate
</a>

                                {% include 'includes/modal.html' with patient_name=d.name patient_id=d.id %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

bloodbank/templates/donor/register.html
{% extends 'index.html' %}
{% load static %}

{% block content %}
<div class="container-fluid torn-sec" 
     style="background-image: url('{% static 'images/torn.jpg' %}');">

    <!-- Overlapping image near the torn edge -->
    <div class="torn-overlay"
         style="background-image: url('{% static 'images/smileinj.jpg' %}');"></div>

    <div class="torn-cont">
        <div class="col-md-4 col-12 form-box">
            <h3 class="subheading">Register</h3>
            {% if error %}
                <div style="color: red;">{{ error }}</div>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username" class="form-label">Name</label>
                    <input type="text" class="form-control" id="username" name="username" autocomplete="off">
                </div>
                <div class="form-group">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" autocomplete="off">
                </div>
                <div class="form-group">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" name="password" autocomplete="off">
                </div>
                <div class="form-group">
                    <label for="confirm_pass" class="form-label">Confirm Password</label>
                    <input type="password" class="form-control" id="confirm_pass" name="confirm_pass" autocomplete="off">
                </div>
                <div class="my-3 d-flex justify-content-center">
                    <button type="submit" class="btn btn-primary regbtn">Register</button>
                </div>
                <div class="my-3 d-flex justify-content-center">
                    <a href="{% url 'bloodbankapp:login' %}" class="loginlink">Already have an account?</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}